### ISSUE TITLE
Add xdg desktop files to tarball

### ISSUE THREAD

**Issue by dvzrv** [pantherb/setBfree#59]
The source tarball doesn't have the XDG desktop files (found in the `debian` folder). As these files are useful on any Linux distribution, they are nothing Debian-specific and should be shipped in a `contrib` folder or similar.

**Comment by x42** [comment]
As noted in debian/changelog, all these files are private for upstream testing only.

Actual downstream [debian packaging] is different. I would rather remove than promote those files.  In particular since `*.desktop` file Categories are not standardized. Distro packagers should also add `*.menu` files if appropriate, this is not under upstream control.

**Comment by x42** [comment]
Actually it was a good time to remove those files since they were unmaintained and no longer relevant upstream.
