### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by geekositalia** [pantherb/setBfree#66]
usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /tmp/x42-whirl.Wm9j1u.ltrans0.ltrans.o: undefined reference to symbol 'g_object_unref'
[  135s] /usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libgobject-2.0.so.0: error adding symbols: DSO missing from command line

Build on openSUSE Tumbleweed.
Building okay on openSUSE Leap

https://build.opensuse.org/package/live_build_log/home:geekositalia:daw/setbfree/openSUSE_Tumbleweed/x86_64

**Comment by x42** [comment]
Likely a bug in libpango that is shipped with SuSE

Can you check if `pkg-config --libs --libs cairo pangocairo pango` returns `-lpangocairo-1.0 -lcairo -lpango-1.0 -lgobject-2.0 -lglib-2.0`?

If it does not include `-lglib-2.0`, please file a bug report with your distribution to update libpango. The issue was fixed upstream already https://gitlab.gnome.org/GNOME/pango/commit/d0cb6be7431d1a3c711bd45bcf05b34601604037

**Comment by geekositalia** [comment]
Thanks for solution! The fix its already on develop repo of gnome, but not pushed on tumbleweed, i include this update on my repo, :) thankyou!
