### ISSUE TITLE
Program Change won't recall user presets

### ISSUE THREAD

**Issue by tassyv** [pantherb/setBfree#76]
Using setBfree in Ardour 5.12 on Linux (Fedora 32)
Using a patch change in my MIDI region, I can successfully recall any of the predefined settings.
However, having stored a user preset in one of the empty banks (like 111 or 118), the plugin doesn't reconfigure properly when triggered via a MIDI program change event.
If a manually recall the preset, then of course it works.
Note that the user preset is visible in the Patch Change dialog in Ardour, I can select it just fine but it just won't load the preset.
![image](https://user-images.githubusercontent.com/36991084/98461616-e0d44a80-21ad-11eb-8c89-2a3fd4e34322.png)
![image](https://user-images.githubusercontent.com/36991084/98461576-876c1b80-21ad-11eb-87bc-6677d5d7e365.png)

**Comment by x42** [comment]
Due to a bug, the list which setBfree shares with Ardour is offset by 1. Ardour starts counting at zero (0..127), while setBfree's list used one (1..128).

In Ardour create a program-change that sends a PC 118.   Selection by name "Vince Idees Noires" incorrectly sends 119.

You can use "a-MIDI Monitor" (comes with ardour) and add the plugin before setBfree to check.

**Comment by argos44** [comment]
loggin in nowadays will stay logged in

one parsec, or light year is alpha centauri. there are 10 on the power of 14 stars in a galaxy. the galactic light emission pattern, or image is a symbol of that galaxy. there are no clusters. its not so big. 1014x1024x1024 unknown measurement units.
Date d’envoi de votre message : Aujourd’hui, à 22:14
they are evenly distributed, normalized, diff at every 2000 years... a lightjump, or warptravel of 2000 parsec implies to experience some sort of emerging, or emenating frequency, mammography, green light, that otherwise does not exist. that is the fifth dimension over

**Comment by argos44** [comment]
shape unknown.... or....

**Comment by argos44** [comment]
check out my non-profit website on music theory

https://dev-wv-sound-system-official-website.pantheonsite.io/

**Comment by argos44** [comment]
l
